# Generated by Django 3.1.3 on 2021-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('time_duration', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
