# Generated by Django 3.1.3 on 2021-06-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.BigIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_answer.question')),
            ],
        ),
    ]
