# Generated by Django 3.1.3 on 2021-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0004_remove_question_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activequestion',
            name='duration',
        ),
    ]
