# Generated by Django 3.1.3 on 2021-06-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0006_auto_20210619_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='active_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question_answer.activequestion'),
            preserve_default=False,
        ),
    ]
